### ISSUE TITLE
Algorithm to impute missing age information

### ISSUE THREAD

**Issue by BoPeng** [magnusdv/pedsuite#2]
I am looking for some algorithm / package to infer missing age in our pedigree data. Depending on the structure of the pedigree, missing age can be estimated from age of parents, siblings, and under the restrictions of age of onset, last followup etc. We could come up with some algorithm by ourselves but we are wondering if pedsuite already has this feature, or if you know of any existing tool for this task. Many thanks in advance.

**Comment by magnusdv** [comment]
Hi,
That's an interesting question. Nothing like that is implemented in the ped suite currently, and I cannot recall having seen it elsewhere either. I'd be interested in knowing what you come up with, though!

**Comment by BoPeng** [comment]
Thanks for your reply. If I am going to write an R function for this, what pedsuite package can I use to load the pedigree, easily access someone's parents and siblings and their information, and save the pedigree back?

**Comment by magnusdv** [comment]
Within the ped suite framwork, pedigrees are represented as `ped` objects, which contains the pedigree info and (optionally) marker genotypes. Pedigrees can be loaded from "ped" files with `readPed()` or built from scratch. The `pedtools` vignette has some examples: https://cran.r-project.org/web/packages/pedtools/vignettes/pedtools.html

Once you have a pedigree, you can find identify all kinds of relatives, e.g.:
``` r
library(pedtools)

# Pedigree with 3 sibs
x = nuclearPed(3)
x
#>  id fid mid sex
#>   1   *   *   1
#>   2   *   *   2
#>   3   1   2   1
#>   4   1   2   1
#>   5   1   2   1
parents(x, 3)
#> [1] "1" "2"
father(x, 3)
#> [1] "1"
siblings(x, 3)
#> [1] "4" "5"
```
The `ped` class does not store age information or other clinical data, so you would have to keep these in a separate container.

**Comment by BoPeng** [comment]
Thank you very much!
